vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        utilisateur:
            uri_prefix: /images/utilisateurs
            upload_destination: '%kernel.project_dir%/public/images/utilisateurs'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        chien:
            uri_prefix: /images/chiens
            upload_destination: '%kernel.project_dir%/public/images/chiens'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer